# Peer review

<h2>

Per‐ and polyfluoroalkyl substances activate UPR pathway, induce steatosis and fibrosis in liver cells

</h2>

<h5>

Qi, Q., Niture, S., Gadi, S., Arthur, E., Moore, J., Levine, K. E., & Kumar, D. (2023)

</h5>

In this part we will look into reproducibilty of scientific publications, we will be doing this by comparing a paper to the criteria that is available on [Researchgate.](https://www.researchgate.net/publication/340244621_Reproducibility_and_reporting_practices_in_COVID-19_preprint_manuscripts)

We will score this paper on the following criteria: Study Purpose, Data Availability Statement, Data Location, Study Location, Author Review, Ethics Statement, Funding Statement and on Code Availability. This is done by filling in the table provided on Researchgate.

The table seen beneath is the table with criteria filled in for the study we chosen above.

+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+
| Transparency Criteria       | Definition                                                                                                                                                                                                                                                               | Response Type       | Score                     |
+=============================+==========================================================================================================================================================================================================================================================================+=====================+===========================+
| Study Purpose               | A concise statement in the introduction of the article, often in the last paragraph, that establishes the reason the research was conducted. Also called the study objective.                                                                                            | Binary              | no                        |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+
| Data Availability Statement | A statement, in an individual section offset from the main body of text, that explains how or if one can access a study's data. The title of the section may vary, but it must explicitly mention data; it is therefore distinct from a supplementary materials section. | Binary              | no                        |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+
| Data Location               | Where the article's data can be accessed, either raw or processed.                                                                                                                                                                                                       | Found Value         | ArrayExpress E‐MTAB‐11670 |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+
| Study Location              | Author has stated in the methods section where the study took place or the data's country/region of origin.                                                                                                                                                              | Binary; Found Value | no                        |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+
| Author Review               | The professionalism of the contact information that the author has provided in the manuscript.                                                                                                                                                                           | Found Value         | Tier 3                    |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+
| Ethics Statement            | A statement within the manuscript indicating any ethical concerns, including the presence of sensitive data.                                                                                                                                                             | Binary              | no                        |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+
| Funding Statement           | A statement within the manuscript indicating whether or not the authors received funding for their research.                                                                                                                                                             | Binary              | yes                       |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+
| Code Availability           | Authors have shared access to the most updated code that they used in their study, including code used for analysis.                                                                                                                                                     | Binary              | no                        |
+-----------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+---------------------------+

The article researches how the retention of fat, fibrogenic signals and cell survival are influenced by low concentrations of three different PFAS in liver cell models. This is done using a handfull of techniques like cell counting and staining, RT qPCR, RNA-seq and others. Important findings are that PFAS in low concentrations can cause ER stress, steatosis and fibrogenic signaling, therefore associating PFAS to the development of non alcoholic fatty liver disease.


